# ===================================
#  Btn  Behavior Config
# ===================================

Description: >
    //startKeep/
modelClass: Waka\ImportExport\Models\Import

workflow: false 

###BREADCRUMP
breadcrump:
    inSettings: true 
    indexUrl: waka/importexport/imports
    indexlabel: waka.importexport::import.title
    title: waka.importexport::import.form_name

###TOOL_BAR
tool_bar:
    base:
        create: 
            show: true
            permissions: [wcli.importexport.admin.*]
            url: waka/importexport/imports/create
        reorder: 
            show: false 
        delete: 
            show: true
            permissions: [wcli.importexport.admin.*]
    config_btns:
            format: all
            btns:
    config_lot:
        format: all
        btns: 
    # partials: #Attention seul les variables modelId et modelClass (class du controller) sont disponible sans les partials.  
    #     testbtns:
    #         url: $/waka/importexport/controllers/imports/_test_btns.htm

###ACTION_BAR Producteurs. Les behavior liée aux boutons doivent êtres instanciés implements = [waka.xxx.behaviors.yyy] dans le controller. 
action_bar:
    config_btns:
        format: grouped #unique : un seul bouton, all : tts les boutons
        groups:
            waka.utils::lang.prod.produce: oc-icon-file-text-o
            waka.utils::lang.prod.send: oc-icon-external-link
            waka.utils::lang.prod.tools: oc-icon-wrench
        btns:
            duplicate:
                config: waka.utils::btns.duplicate
                group: waka.utils::lang.prod.tools

    # partials: #Attention seul les variables modelId et modelClass (class du controller) sont disponible sans les partials.  
    #     name:
    #         url: $/waka/importexport/controllers/imports/_test_update.htm
Description: >
    //endKeep/


#     ##### SAUVEGARDE PURE ########

# modelClass: Waka\ImportExport\Models\Import

# workflow: false 

# ###BREADCRUMP
# breadcrump:
#     inSettings: true 
#     indexUrl: waka/importexport/imports
#     indexlabel: waka.importexport::import.title
#     title: waka.importexport::import.form_name

# ###TOOL_BAR
# tool_bar:
#     base:
#         create: 
#             show: true
#             permissions: [wcli.importexport.admin.*]
#             url: waka/importexport/imports/create
#         reorder: 
#             show: false#  
#         delete: 
#             show: true
#             permissions: [wcli.importexport.admin.*]
#     config_btns:
#             format: all
#             btns:
# # #     config_lot:
#         format: all
#         btns: 
# # # # #     # partials: #Attention seul les variables modelId et modelClass (class du controller) sont disponible sans les partials.  
#     #     testbtns:
#     #         url: $/waka/importexport/controllers/imports/_test_btns.htm

# ###ACTION_BAR Producteurs. Les behavior liée aux boutons doivent êtres instanciés implements = [waka.xxx.behaviors.yyy] dans le controller. 
# action_bar:
#     config_btns:
#         format: grouped #unique : un seul bouton, all : tts les boutons
#         groups:
#             waka.utils::lang.prod.produce: oc-icon-file-text-o
#             waka.utils::lang.prod.send: oc-icon-external-link
#             waka.utils::lang.prod.tools: oc-icon-wrench
#         btns:
# # # # # #             duplicate:
#                 config: waka.utils::btns.duplicate
#                 group: waka.utils::lang.prod.tools
# # # # # # 
#     # partials: #Attention seul les variables modelId et modelClass (class du controller) sont disponible sans les partials.  
#     #     name:
#     #         url: $/waka/importexport/controllers/imports/_test_update.htm
