# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Type

# Model Form Field configuration
form: $/waka/importexport/models/type/fields.yaml

# Model Class name
modelClass: Waka\ImportExport\Models\Type

# Default redirect location
defaultRedirect: waka/importexport/types

# Create page
create:
    title: Create Import Type
    redirect: waka/importexport/types/update/:id
    redirectClose: waka/importexport/types

# Update page
update:
    title: Edit Import Type
    redirect: waka/importexport/types
    redirectClose: waka/importexport/types

# Preview page
preview:
    title: Preview Import Type
