# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Config Import

# Model Form Field configuration
form: $/waka/importexport/models/configimport/fields.yaml

# Model Class name
modelClass: Waka\ImportExport\Models\ConfigImport

# Default redirect location
defaultRedirect: waka/importexport/configimports

# Create page
create:
    title: Create Config Import
    redirect: waka/importexport/configimports/update/:id
    redirectClose: waka/importexport/configimports

# Update page
update:
    title: Edit Config Import
    redirect: waka/importexport/configimports
    redirectClose: waka/importexport/configimports

# Preview page
preview:
    title: Preview Config Import
