# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.importexport::export.form_name

# Model Form Field configuration
form: $/waka/importexport/models/export/fields.yaml

# Model Class name
modelClass: Waka\ImportExport\Models\Export

# Default redirect location
defaultRedirect: waka/importexport/exports

# Create page
create:
    title: waka.importexport::export.create
    redirect: waka/importexport/exports/update/:id
    redirectClose: waka/importexport/exports
    form: $/waka/importexport/models/export/fields_create.yaml

# Update page
update:
    title: waka.importexport::export.update
    redirect: waka/importexport/exports
    redirectClose: waka/importexport/exports

# Preview page
preview:
    title: waka.importexport::export.preview_name
