# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Import Type

# Model Form Field configuration
form: $/waka/importexport/models/importtype/fields.yaml

# Model Class name
modelClass: Waka\ImportExport\Models\ImportType

# Default redirect location
defaultRedirect: waka/importexport/importtypes

# Create page
create:
    title: Create Import Type
    redirect: waka/importexport/importtypes/update/:id
    redirectClose: waka/importexport/importtypes

# Update page
update:
    title: Edit Import Type
    redirect: waka/importexport/importtypes
    redirectClose: waka/importexport/importtypes

# Preview page
preview:
    title: Preview Import Type
